# -*- coding: utf-8 -*-
"""toy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1668ro8GkHjvVtzSNciS5ktCm76EVfvM2
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/sample_data/placement.csv')

df.head()

df.shape

df.info()

"""# steps
#preprocess + eda + feature selection
#scale the values
#train test spilit
#train the model
#evaluate the model
#deploye the model
"""

df = df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'], c=df['placement'])

x = df.iloc[:,0:2]
y= df.iloc[:,-1]

x

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_train

x_test = scaler.transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

#model training
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train, y_train.values , clf=clf, legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))

from google.colab import drive
drive.mount('/content/drive')